---
# Default configuration
baseURL: https://theslgcompany.com
canonifyURLs: true
enableEmoji: true
enableGitInfo: false
pygmentsCodefences: true
pygmentsUseClasses: true
languageCode: "en-us"
defaultContentLanguage: en
enableRobotsTXT: true

disableKinds:
  - "RSS"

# Directories
archetypeDir: archetypes
contentDir: content
dataDir: data
publishDir: public
staticDir: static
layoutdir: layouts
assetDir: assets

# Theme
theme: "hermit"

# Languages
languages:
  en:
    languageName: English
    languageCode: en
    contentDir: content/
    weight: 1

# Params
author:
  name: "#THESLGCOMPANY"

params:
  customCSS: ["css/custom.css"]
  dateform: "Jan 2, 2006"
  dateformShort: "Jan 2"
  dateformNum: "2006-01-02"
  dateformNumTime: "2006-01-02 15:04 -0700"
  themeColor: "#e52920"
  bgImg: "https://s3.eu-north-1.amazonaws.com/theslgcompany.com/theslgcompany-background.jpg"
  social:
    # - name: "twitter"
    #   url: "https://twitter.com/theslgcompany"
    - name: "instagram"
      url: "https://instagram.com/theslgcompany"
    - name: "github"
      url: "https://github.com/slgevens/theslgcompany.com"
    - name: "email"
      url: "mailto:info@theslgcompany.com"
    # - name: "cart"
    #   url: "https://theslgstore.com"

